# Generated by Django 5.0.4 on 2025-05-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_marketingcampaign_partnercompany_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="category",
            field=models.CharField(
                choices=[
                    ("sports", "Sports"),
                    ("art", "Art"),
                    ("language", "Language"),
                    ("music", "Music"),
                    ("others", "Others"),
                ],
                default="others",
                max_length=20,
            ),
        ),
    ]
