# Generated by Django 5.0.4 on 2025-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                choices=[
                    ("Kadıköy", "Kadıköy"),
                    ("Üsküdar", "Üsküdar"),
                    ("Ataşehir", "Ataşehir"),
                    ("Maltepe", "Maltepe"),
                    ("Kartal", "Kartal"),
                    ("Pendik", "Pendik"),
                    ("Tuzla", "Tuzla"),
                    ("Sancaktepe", "Sancaktepe"),
                    ("Çekmeköy", "Çekmeköy"),
                ],
                default="Kadıköy",
                max_length=100,
            ),
        ),
    ]
