# Generated by Django 5.0.4 on 2025-05-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default_avatar.png",
                upload_to="profile_images/",
            ),
        ),
    ]
