# Generated by Django 5.0.4 on 2025-05-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default_pikachu.png",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
