# Generated by Django 5.0.4 on 2025-05-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="venue_logos/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default_avatar.png",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
