# Generated by Django 5.0.4 on 2025-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_venue_logo_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
