# Generated by Django 5.0.4 on 2025-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_venue_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnercompany",
            name="type",
            field=models.CharField(
                choices=[
                    ("place", "Place for Meeting"),
                    ("company", "Corporate Partner"),
                ],
                default="company",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="type",
            field=models.CharField(
                choices=[("place", "Meeting Place"), ("company", "Discount Provider")],
                default="place",
                max_length=20,
            ),
        ),
    ]
