# Generated by Django 5.2 on 2025-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_partnercompany_type_venue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnercompany",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="partner_logos/"),
        ),
    ]
