# Generated by Django 5.2 on 2025-05-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_partnercompany_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
