# Generated by Django 5.2 on 2025-05-28 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_matchfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
